### PR TITLE
Added pagination container HOC

### PR DESCRIPTION
**Pull request by MartinDawson**

### CODE REVIEW

**Comment by MartinDawson** [comment]
@ErrorPro Please also update the npm package to a minor version with this change. Thanks.

**Comment by ErrorPro** [comment]
@MartinDawson Everything looks good, but please change package.json back(at least urls) and I will merge this PR. Thanks for your PR btw.

**Comment by MartinDawson** [comment]
@ErrorPro Didn't mean to push them changes to package.json on this PR, my bad. It's because we needed these changes so i created a different npm package + repo.

**Comment by ErrorPro** [comment]
@MartinDawson Could you please remove them from this PR? And I will merge it asap.

**Comment by ErrorPro** [comment]
Github does not notify me when something is changed in this repo, so I missed your messages.

**Comment by ErrorPro** [comment]
@MartinDawson  added to @1.0.7. Thank you.

**Pull request closed without merging**
